# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_src/tsp_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1173, 753)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.newMapaButton = QtWidgets.QPushButton(self.frame)
        self.newMapaButton.setObjectName("newMapaButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.newMapaButton)
        self.cargarMapaButton = QtWidgets.QPushButton(self.frame)
        self.cargarMapaButton.setObjectName("cargarMapaButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cargarMapaButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.algoritmoLabel = QtWidgets.QLabel(self.frame)
        self.algoritmoLabel.setObjectName("algoritmoLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.algoritmoLabel)
        self.algoritmoComboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algoritmoComboBox.sizePolicy().hasHeightForWidth())
        self.algoritmoComboBox.setSizePolicy(sizePolicy)
        self.algoritmoComboBox.setObjectName("algoritmoComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.algoritmoComboBox)
        self.itLabel = QtWidgets.QLabel(self.frame)
        self.itLabel.setObjectName("itLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.itLabel)
        self.itSpinBox = QtWidgets.QSpinBox(self.frame)
        self.itSpinBox.setMinimum(1)
        self.itSpinBox.setMaximum(1000)
        self.itSpinBox.setProperty("value", 50)
        self.itSpinBox.setObjectName("itSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.itSpinBox)
        self.itSCLabel = QtWidgets.QLabel(self.frame)
        self.itSCLabel.setObjectName("itSCLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.itSCLabel)
        self.itSCBox = QtWidgets.QSpinBox(self.frame)
        self.itSCBox.setMinimum(1)
        self.itSCBox.setMaximum(1000)
        self.itSCBox.setProperty("value", 20)
        self.itSCBox.setObjectName("itSCBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.itSCBox)
        self.nhLabel = QtWidgets.QLabel(self.frame)
        self.nhLabel.setObjectName("nhLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.nhLabel)
        self.nhSCBox = QtWidgets.QSpinBox(self.frame)
        self.nhSCBox.setMinimum(1)
        self.nhSCBox.setMaximum(50)
        self.nhSCBox.setProperty("value", 10)
        self.nhSCBox.setObjectName("nhSCBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.nhSCBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(13, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.ejecutarButton = QtWidgets.QPushButton(self.frame)
        self.ejecutarButton.setObjectName("ejecutarButton")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.ejecutarButton)
        self.mapaComboBox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapaComboBox.sizePolicy().hasHeightForWidth())
        self.mapaComboBox.setSizePolicy(sizePolicy)
        self.mapaComboBox.setObjectName("mapaComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mapaComboBox)
        self.mapaLabel = QtWidgets.QLabel(self.frame)
        self.mapaLabel.setObjectName("mapaLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mapaLabel)
        self.gridLayout.addWidget(self.frame, 0, 1, 2, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(300, 300))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.informacionWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.informacionWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.informacionWidget.setObjectName("informacionWidget")
        self.infoTab = QtWidgets.QWidget()
        self.infoTab.setObjectName("infoTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.infoTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.infoText = QtWidgets.QTextBrowser(self.infoTab)
        self.infoText.setObjectName("infoText")
        self.gridLayout_2.addWidget(self.infoText, 0, 0, 1, 1)
        self.informacionWidget.addTab(self.infoTab, "")
        self.ejecucionTab = QtWidgets.QWidget()
        self.ejecucionTab.setObjectName("ejecucionTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ejecucionTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ejecucioText = QtWidgets.QTextBrowser(self.ejecucionTab)
        self.ejecucioText.setObjectName("ejecucioText")
        self.gridLayout_3.addWidget(self.ejecucioText, 0, 0, 1, 1)
        self.informacionWidget.addTab(self.ejecucionTab, "")
        self.gridLayout.addWidget(self.informacionWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1173, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.informacionWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TSP ACO"))
        self.newMapaButton.setText(_translate("MainWindow", "Nuevo mapa"))
        self.cargarMapaButton.setText(_translate("MainWindow", "Cargar mapa"))
        self.algoritmoLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Algoritmo</p></body></html>"))
        self.itLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Max iterciones</p></body></html>"))
        self.itSCLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Max iteraciones sin cambios</p></body></html>"))
        self.nhLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Hormigas</p></body></html>"))
        self.ejecutarButton.setText(_translate("MainWindow", "ejecutar"))
        self.mapaLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mapa</p></body></html>"))
        self.infoText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.informacionWidget.setTabText(self.informacionWidget.indexOf(self.infoTab), _translate("MainWindow", "información"))
        self.informacionWidget.setTabText(self.informacionWidget.indexOf(self.ejecucionTab), _translate("MainWindow", "ejecución"))

